server:
  port: 8081

spring:
  application:
    name: book-service
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/books

  profiles:
    active: dev

  config:
    import: 'optional:configserver:'

  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    preferIpAddress: true
